### ISSUE TITLE
"Unauthorized" when trying to open/download a book with LDAP login and opds

### ISSUE THREAD

**Issue by mmguero** [janeczku/calibre-web#1435]
**Description**

To be upfront, I think this is much more likely an issue with either my configuration or Moon+ Reader Pro than calibre-web itself, but I'm hoping that perhaps you or someone here who has had a similar issue could help me resolve it.

I'm using a [Docker container of my own creation ](https://github.com/mmguero/docker/blob/master/services/calibre-web/docker/Dockerfile) based on [linuxserver/docker-calibre-web](https://github.com/linuxserver/docker-calibre-web). I am using [LDAP Login](https://github.com/janeczku/calibre-web/wiki/LDAP-Login).

I was running into https://github.com/janeczku/calibre-web/issues/1403 up until a few days ago, but your fix has resolved that (for most categories; for some I am still getting the OPDS content error, but that's not the focus of this issue).

**Steps to Reproduce**

Here's what I'm doing:

1. In Moon+ Reader Pro, go to *Net Library*
2. *Add new catalog*, click *Calibre IP* and enter the Calibre server connection information
3. Supply username and password (in my case, I'm using LDAP Login; I'm able to successfully log in)
4. The contents of my library are displayed; click any category (e.g., *Recently added Books*)
5. Books are listed, click on any book
6. An "Unauthorized" screen is shown without any other information

I don't see any useful information from my Docker logs. I don't see any useful information via the Calibre-Web GUI display of the calibre-logs, either. I could try to figure out how to increase log verbosity perhaps (?).

**Screenshots**

![Screenshot_20200526-092025](https://user-images.githubusercontent.com/13872653/82918864-895d5d80-9f32-11ea-8c0a-6096e553f54b.png)
![Screenshot_20200526-092043](https://user-images.githubusercontent.com/13872653/82918868-89f5f400-9f32-11ea-86a4-cf58bfe2f64a.png)
![Screenshot_20200526-092104](https://user-images.githubusercontent.com/13872653/82918869-8a8e8a80-9f32-11ea-9786-a4157af4b8c3.png)
![Screenshot_20200526-092122](https://user-images.githubusercontent.com/13872653/82918870-8a8e8a80-9f32-11ea-8455-138aad530acc.png)
![Screenshot_20200526-092126](https://user-images.githubusercontent.com/13872653/82918872-8b272100-9f32-11ea-858e-f6ab51fafcc6.png)
![Screenshot_20200526-092130](https://user-images.githubusercontent.com/13872653/82918877-8bbfb780-9f32-11ea-99c6-e3b3c03cb739.png)
![Screenshot_20200526-092134](https://user-images.githubusercontent.com/13872653/82918881-8c584e00-9f32-11ea-9c1f-28ed634f926f.png)

**Environment (please complete the following information):**
 - Calibre-Web version 0.6.7
 - Docker container [based on](https://github.com/mmguero/docker/blob/master/services/calibre-web/docker/Dockerfile) [linuxserver/docker-calibre-web](https://github.com/linuxserver/docker-calibre-web)
 - Browser [Moon+ Reader Pro](https://play.google.com/store/apps/details?id=com.flyersoft.moonreaderp&hl=en_US)

**Additional context**
Access via [LDAP Login](https://github.com/janeczku/calibre-web/wiki/LDAP-Login).

**Comment by mmguero** [comment]
I turned on DEBUG level logs an access log.

I don't get anything in the debug logs, but the access log shows this when, in moon reader, I

1. Open Net Library
2. Click on Calibre-Web
3. Click on recently added
4. Click on a book title and see "Unauthorized"

```
172.16.0.3 - - [2020-05-26 10:56:43] "GET /opds HTTP/1.1" 401 191 0.003845
172.16.0.3 - - [2020-05-26 10:56:43] "GET /opds HTTP/1.1" 401 191 0.007705
172.16.0.3 - - [2020-05-26 10:56:44] "GET /opds HTTP/1.1" 200 4595 0.727163
172.16.0.3 - - [2020-05-26 10:56:44] "GET /opds/osd HTTP/1.1" 401 191 0.005018
172.16.0.3 - - [2020-05-26 10:56:45] "GET /opds/new HTTP/1.1" 401 191 0.008437
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/new HTTP/1.1" 200 76653 0.706223
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/osd HTTP/1.1" 401 191 0.008229
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/cover/2749 HTTP/1.1" 401 191 0.007398
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/cover/2748 HTTP/1.1" 401 191 0.004216
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/cover/2747 HTTP/1.1" 401 191 0.005268
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/cover/2746 HTTP/1.1" 401 191 0.004729
172.16.0.3 - - [2020-05-26 10:56:46] "GET /opds/cover/2745 HTTP/1.1" 401 191 0.003880
172.16.0.3 - - [2020-05-26 10:56:47] "GET /opds/cover/2749 HTTP/1.1" 401 191 0.009908
```

**Comment by OzzieIsaacs** [comment]
I have to take a look at it. There are two possibilities, moon reader forgets to send the credentials (some of the opds reader tend to do this, especially for cover downloads), or Calibre-Web isn't handling the credentials properly (the message you see could point to this) The message isn't created by calibre-web itself, but from some of the underlying imports.

**Comment by OzzieIsaacs** [comment]
Thanks for all the information. I think they give me a good starting point for what to look after.

**Comment by mmguero** [comment]
Hey, I thought of one more thing: I tried disabling LDAP login in favor of using the standard login mechanism. I get the same results, however, instead of "Unauthorized" the error message is "Could not verify your access level for that URL. You have to login with proper credentials"

I hope that is helpful.

**Comment by mmguero** [comment]
Also, FWIW I did just try it with fbreader instead and everything worked fine. So it may be there's not much you can do.

**Comment by OzzieIsaacs** [comment]
My wiki states that moon reader had problems with covers:
https://github.com/janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web
One question: Which version of moon reader are you using? (the newest one, 5.2.9?)

**Comment by mmguero** [comment]
Yes, I am using v5.2.9. Updated last week, I think.

**Comment by mmguero** [comment]
Ah, I see the note about anonymous browsing. With my current setup I'm not inclined to enable anonymous browsing. However, a workaround for me could be to use FBReader to download books and have Moon+ Reader automatically import books from FBReader's download folder (as I prefer Moon+ Reader for the actual reading, but I don't really care if I have to use fbreader as just a catalog/download utility). That's not a huge burden.

**Comment by cbartondock** [comment]
This is still an issue with Moon Reader + and it looks to also be an issue with fbReader also in the newest versions. I get a 401 response when trying to view covers and either a 401 or a 403 when trying to download books (the 403 looks to be coming from calibre-web, and yes my user is authorized to download books).

![Capture](https://user-images.githubusercontent.com/4482454/96506241-4c696e80-1225-11eb-9227-b221fcbc2dc4.PNG)

**Comment by cbartondock** [comment]
I have also confirmed that this probably is an issue with Calibre Web rather than the app on the other side, since using the OPDS feed from Calibre Server works fine in any of the aforementioned apps.

**Comment by tmechen** [comment]
i think this might not only be a problem with moonreader.  
im encountering the same problem with kyreader3 on ios.  
adding opds library works like a charm, i can browse the books and see all covers.  
but once i try to download a book (with a user with download rights) i am seeing 403 forbidden

both in the app  
![image](https://user-images.githubusercontent.com/9123876/100519585-368e8800-3199-11eb-97a1-7a693d15ca88.png)

and in the access logs:
![image](https://user-images.githubusercontent.com/9123876/100519618-6d649e00-3199-11eb-9776-11d91337bec8.png)


whats even more strange:  
trying to reproduce this with my browser, i can download the epub without problems
(login with the same user, following the opds link)

![image](https://user-images.githubusercontent.com/9123876/100519666-ba487480-3199-11eb-92e9-f0d1ac262f76.png)


ima look into the packages and update further

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply, I can now reproduce it in combination with ldap login

**Comment by OzzieIsaacs** [comment]
Okay, I think I could fix it: 
3 prerequisites had to be fullfilled:
- Login provided has to be LDAP 
- cookie has to be present on opds request 
- download route had to be triggered

**Comment by cbartondock** [comment]
Are you saying this is fixed? I would love to not be running CalibreServer at the same time as CalibreWeb, which was my solution to this issue.

**Comment by OzzieIsaacs** [comment]
Yes it‘s fixed and getting tested for staying fixed

**Comment by cbartondock** [comment]
Woohoo! Thanks for all your hard work man.

**Comment by Daniel15** [comment]
> My wiki states that moon reader had problems with covers:
> [janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web](https://github.com/janeczku/calibre-web/wiki/FAQ#which-opds-readers-work-with-calibre-web)

@OzzieIsaacs Sorry for bumping an old thread, but this issue is still one of the top results in Google for "Calibre-web Moon+ Reader cover not loading"

I worked around this issue with Moon+ Reader by getting my Nginx reverse proxy to send a hard-coded `Authentication` header for URLs under `/opds/covers/`, so that Calibre-Web *thinks* a username and password was entered. I added a new user in Calibre-Web with all permissions disabled, then added a block in my Nginx config for `/odps/covers/` with a line like this:

```
proxy_set_header Authorization "Basic YW5vbmNvdmVyczpoZWxsb3dvcmxk==";
```
where `YW5vbmNvdmVyczpoZWxsb3dvcmxk` is `username:password` encoded as Base64 (username `anoncovers`, password `helloworld` in this example)


For example, for LinuxServer.io's `calibre-web.subfolder` Nginx config, I added this block at the end:

```
location ^~ /calibre-web/opds/cover/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app calibre-web;
    set $upstream_port 8083;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    proxy_set_header X-Scheme $scheme; 
    proxy_set_header X-Script-Name /calibre-web;
    proxy_set_header Authorization "Basic YW5vbmNvdmVyczpoZWxsb3dvcmxk==";
}
```
(with the correct username and password of course).

Is it OK if I document this in the FAQ?
