### ISSUE TITLE
Overly large margins when reading epub on mobile

### ISSUE THREAD

**Issue by slikts** [janeczku/calibre-web#1526]
Epub reader margins are too large on mobile:
![image](https://user-images.githubusercontent.com/137872/87328470-30777200-c53e-11ea-9641-d0f2cf2ba637.png)

It's unclear why the margins would need to be so large and limit the readable area to a small square in the middle. It seems like an oversight, and I've not found a way to configure it.

The environment is using the current LinuxServer calibre-web image.

**Comment by Donatzsky** [comment]
The problem is that, for some reason, there's lot of special-casing for iOS devices in the CSS.

The code in question starts at line 698 (`/* For iPad portrait layouts only */`) here:
https://github.com/janeczku/calibre-web/blob/master/cps/static/css/main.css

Really not sure why it's been done like this.

**Comment by negativzeroe** [comment]
So can we have the ability to shrink the margins and text size? How would we go about this, turn it into a feature request?

**Comment by OzzieIsaacs** [comment]
> Really not sure why it's been done like this.
Me, too. 2 posibilities: 
A) At some point in time I added it based on my iPad layout at that time
B) It was part of the epub reader package and just was copied.

Feel free to change it

**Comment by OzzieIsaacs** [comment]
One remark: There is a request about to small text sizes in the reader on kindle, so if you change it, please don't just change the size, but make it adjustable

**Comment by negativzeroe** [comment]
I don't mind adjusting, IMHO it should be in the ui config section of the admin panel, hence the thought of turning it into a feature request. But I can't find it in the file system in the container or I'd map it and adjust there.

**Comment by zoenglinghou** [comment]
I do not think this is a CSS-only issue. By messing around the stylesheet (using userstyles), It seems that we need to adjust the embedded content inside the iframe as well, otherwise the content would stubbornly stays at a small frame. See for yourself:

```css
@-moz-document regexp("^https://<your-website-here>/read/.*") {
    @media only screen and (min-device-width: 375px) and (max-device-width: 667px) and (orientation: portrait) {
        #viewer {
            width: 80% !important;
            height: 85% !important;
        }

        #viewer iframe {
            width: 80vw !important;
            height: 100% !important;
        }
        
        div.epub-view {
            height: 85vh !important;
        }
    }
}
```

**Comment by n00b12345** [comment]
Facing this issue. Wish there was a solution.

**Comment by brodie-g** [comment]
I think this is still an issue. Viewing the epub reader on a mobile device (Android Pixel 6 Pro in my case) results in huge bottom margin (about half the screen height). Makes mobile reading nearly unusable.

This may also be an issue with the underlying epubjs reader library, I see the same behaviour using their demo app - https://futurepress.github.io/epubjs-reader/ - loading the reader in the mobile view using the browser dev tools. I also see the large bottom margin.

Surely there's a way to set the height of the reader when it's loaded to use the entire height of the screen? Any help or guidance would be great. I could look into making a PR if someone can point me in the right direction.

**Comment by OzzieIsaacs** [comment]
Meanwhile I‘m thinking of replacing the epub.js library as it seems it is no longer maintained. I don‘t know how long this will take and if it‘s worth spending time on improving the current reader

**Comment by brodie-g** [comment]
Shame. It's a good reader for the most part, but development of it does seemed to have stopped.

Just did a little search around for what else is out there.

Here's a fork of epubjs that looks promising - https://github.com/intity/epub-js. The UI has a number of nice improvements, with the side bar and settings. Specifically the issues with the mobile margins are fixed :D . Demo https://intity.github.io/epubreader-js/

Can't speak to its long term plans or reliability though, so might be risky.

**Comment by OzzieIsaacs** [comment]
I might have stumbled over it but had problems implementing it, there had been issues with the inner epub links to work and I stopped working at it.
The main problem with the current one is from my point of view that bookmarks are depending on the screens size, so a bookmarked page 3 on a 2k screen will never be found again on a 1024x768 screen, making this feature worthless

**Comment by Donatzsky** [comment]
There's foliate-js which, if I remember correctly, was designed to be mostly a drop-in replacement. In any case it's actively developed and used in the Foliate reader app.
https://github.com/johnfactotum/foliate-js

**Comment by themeadery** [comment]
Hi, I have this same issue. I tried requesting the desktop version of the site with the slider in Firefox mobile, but it doesn't fix it. Can we get a bump on priority on this? It's only been 5 years....

**Comment by irvingoujAtDevolution** [comment]
Can I take this issue? I'll fix for IOS devices specifically because that's the only mobile device I have

**Comment by OzzieIsaacs** [comment]
@irvingoujAtDevolution you are welcome to do so

**Comment by IT-RT** [comment]
I am facing the same issue, and would love to see a way to fix this.
