### ISSUE TITLE
Fetch Metadata no longer working - returns 'search error!'

### ISSUE THREAD

**Issue by kaipee** [janeczku/calibre-web#2139]
**Describe the bug/problem**
'Fetch Metadata' function returns 'search error!'

**To Reproduce**
1. Go to any book
2. Click on 'Fetch Metadata'
3. Google and ComicVine options are shown
4. No results are shown, only 'search error!' in red with an empty list.

**Logfile**
Not sure if relevant, but these are the last lines of the error log.
```
[2021-10-17 13:20:12,076]  WARN {cps.converter:45} /opt/calibre/ebook-convert: module 're' has no attribute 'Match'
[2021-10-17 13:21:01,988]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:06,377]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:18,852]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:27,903]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:34,331]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:35,347]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:21:36,483]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:23:40,507]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:23:44,238]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:25:18,118]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:28:11,640]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 13:33:57,203]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
```

**Expected behavior**
Search results for metadata.

**Screenshots**
![image](https://user-images.githubusercontent.com/5189160/137627585-fa81ff88-5a08-4857-a3d1-488fe052350b.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 1804
 - Python version: python 3.5.2
 - Calibre-Web version: dcba720
 - Docker container:  None

**Comment by OzzieIsaacs** [comment]
Sorry the version you've linked is a version from Feb.2020, so this can't be valid. 

With my current nightly version I can't reproduce this (but absolute plausible, that it's not working in your version, I found some minor problems in the last days, which I've fixed)

**Comment by kaipee** [comment]
Hmm, yes I can see that links to an old version but that _is_ the version being returned.

![image](https://user-images.githubusercontent.com/5189160/137629585-996b4bd1-101d-481e-8e87-8653c0be8e5e.png)

```
root@calibre:/opt/calibre-web# git rev-parse --short HEAD
dcba720
```

**Comment by OzzieIsaacs** [comment]
Ah, so you cloned it initially and now using the in program updater. Then git has no knowledge about the change and continues to output the old git revision.
Are you using a reverse proxy? Could you please try to access calibre-web directly and check if the update/Metadata load is working then?

**Comment by kaipee** [comment]
Works fine on local LAN. I presume there is some CSRF header that needs added?

![image](https://user-images.githubusercontent.com/5189160/137630389-7a690bb6-1e4a-4573-802c-2acbed77adbf.png)

**Comment by kaipee** [comment]
Still doesn't seem to work.

```
[2021-10-17 15:11:39,495]  INFO {cps.server:257} Performing shutdown of Calibre-Web
[2021-10-17 15:11:45,234] ERROR {cps.search_metadata:51} Import error for metadata source: scholar
[2021-10-17 15:11:45,256]  INFO {cps:129} Starting Calibre Web...
[2021-10-17 15:11:45,433]  INFO {cps.server:226} Starting Tornado server on :8083
[2021-10-17 15:12:32,154]  INFO {flask_wtf.csrf:258} The CSRF token is missing.
[2021-10-17 15:12:48,157]  INFO {cps.admin:1669} Update status requested
```

![image](https://user-images.githubusercontent.com/5189160/137631190-589768ca-1d8d-4370-9b98-35f65d8cd937.png)

**Comment by kaipee** [comment]
I've added the following to NGINX proxy, but still no fix.

```
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-Host    $host:$server_port;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_set_header        X-Forwarded-Ssl     on;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Server  $host;
        proxy_set_header        X-Scheme            $scheme;
```

**Comment by OzzieIsaacs** [comment]
For me it's working now. Could you please check on the developer console if the CSRF token is there:
![grafik](https://user-images.githubusercontent.com/6438895/137632151-452b9741-a307-4e8d-bea1-c28c4083224c.png)
"Search" request and then in the request header there should be a X-CSRFToken

**Comment by kaipee** [comment]
CSRF element does seem to be there (3 locations), but still same issue with private tab.

```
<form id="form-upload" class="navbar-form" action="/upload" data-title="Uploading..." data-footer="Close" data-failed="Error" data-message="Upload done, processing, please wait..." method="post" enctype="multipart/form-data">
<input type="hidden" name="csrf_token" value="IjFlOTdiNWIyODBkYTA4ZGY4Mzg2MWYxNzM3NGZkOWFmOTUxZWZjMTci.YWw-0A.6PNGVB_lj311SJbN3MRBKe28uiM">
<div class="form-group">
```

```
<div class="text-center more-stuff"><h4>Convert book format:</h4>
<form class="padded-bottom" action="/admin/book/convert/560" method="post" id="book_convert_frm">
<input type="hidden" name="csrf_token" value="IjFlOTdiNWIyODBkYTA4ZGY4Mzg2MWYxNzM3NGZkOWFmOTUxZWZjMTci.YWw-0A.6PNGVB_lj311SJbN3MRBKe28uiM">
<div class="form-group">
```

```
<form role="form" action="/admin/book/560" method="post" enctype="multipart/form-data" id="book_edit_frm">
<input type="hidden" name="csrf_token" value="IjFlOTdiNWIyODBkYTA4ZGY4Mzg2MWYxNzM3NGZkOWFmOTUxZWZjMTci.YWw-0A.6PNGVB_lj311SJbN3MRBKe28uiM">
<div class="col-sm-9 col-xs-12">
```

**Comment by blumarten** [comment]
I just started having this problem. I'm on the latest version. Same issue if I access over cloudflare or locally, and if i log in through an incognito window. Hoping it might magically fix itself at some point, but happy to hear anything to try in the meantime
