### ISSUE TITLE
Attempting to use Gmail Account with oAuth Verification causes Calibre-Web to become unresponsive

### ISSUE THREAD

**Issue by delize** [janeczku/calibre-web#2254]
**Describe the bug/problem**
Calibre-Web interface stops responding when navigating to https://domain/calibre-web/admin/mailsettings when attempting to use Google oAuth interface.

**To Reproduce**
1. Go to https://domain.org/calibre-web/admin/mailsettings
2. Change Server Type from `Standard E-mail account` to `Gmail account with oAuth`
3. Click `Setup Gmail Account as E-Mail Server`
4. Calibre-web crashes and does not open the oAuth tab.

**Logfile**
This is with debug context started:
```
[2022-01-03 22:43:10,223]  INFO {cps:134} Starting Calibre Web...
[2022-01-03 22:43:10,329]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2022-01-04 12:10:27,001] DEBUG {cps.ub:94} Found stored session: db57a252b3e3ec703e12a0ab4d0e8834ef28afc39f0cb57201c92a1301d93b19093359a606889c4b6dc356972541f88e3b410ea7c2495b775a5d26f83257a720
[2022-01-04 12:10:27,002] DEBUG {cps.ub:94} Found stored session: db57a252b3e3ec703e12a0ab4d0e8834ef28afc39f0cb57201c92a1301d93b19093359a606889c4b6dc356972541f88e3b410ea7c2495b775a5d26f83257a720
[2022-01-04 12:10:27,002] DEBUG {cps.web:1567} You are now logged in as: 'andrew'
[2022-01-04 12:10:31,201] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
[2022-01-04 12:11:17,306]  INFO {cps.server:272} webserver stop (restart=False)
[2022-01-04 12:11:35,294]  INFO {cps:134} Starting Calibre Web...
[2022-01-04 12:11:35,400]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2022-01-04 12:14:30,623]  INFO {cps.server:272} webserver stop (restart=False)
[2022-01-04 12:14:46,921]  INFO {cps:134} Starting Calibre Web...
[2022-01-04 12:14:47,032]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2022-01-04 12:14:52,936] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
[2022-01-04 12:21:23,386]  INFO {cps.server:272} webserver stop (restart=False)
[2022-01-04 12:21:39,553]  INFO {cps:134} Starting Calibre Web...
[2022-01-04 12:21:39,658]  INFO {cps.server:204} Starting Gevent server on [::]:8083
[2022-01-04 12:23:24,121] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
[2022-01-04 12:23:33,084] DEBUG {cps.updater:332} Stable version: {'version': '0.6.14'}
```

**Expected behavior**
Open up Google oAuth flow to validate the Service Account

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10/Raspberry Pi OS]  

```
cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```

 - Python version: [e.g. python2.7]
```
$python3 --version
Python 3.8.10
```
 - Calibre-Web version: 0.6.14 - 4da64ceb23e69da3953f9c454ea261d9d0621e25 - 2021-10-31T11:31:53+01:00
 - Docker container:  LinuxServer
 - Special Hardware: N/A
 - Browser: Chrome: Version 96.0.4664.110 (Official Build) (x86_64)

**Additional context**

https://github.com/janeczku/calibre-web/issues/2179 - Seems related to the issue
I have attempted to clear the app.db file and start from scratch - this does not seem to help resolve the issue. 

```
![image](https://user-images.githubusercontent.com/4028612/148107636-bebacee0-a2c8-4fb1-a620-c87548d28bc9.png)

![image](https://user-images.githubusercontent.com/4028612/148107678-3604a856-51b2-457f-ab09-d611c54f9d50.png)

**Comment by OzzieIsaacs** [comment]
This is a problem in the docker container. The gmail authentification workflow is supposed to open a random port, an start a server there for receiving the gmail answer, this doesn't work in the container (is block and not forseable as it's a random port)

**Comment by delize** [comment]
So by default if it opens a random port, can you open a specific port via an Env variable?

There are also alternatives for oAuth flows:
https://stackoverflow.com/questions/47269124/gmail-oauth-from-within-docker-container
https://stackoverflow.com/questions/37243862/send-mail-via-google-apps-gmail-using-service-account-domain-wide-delegation-in
https://stackoverflow.com/questions/61665467/how-to-authenticate-with-gmail-api-from-node-container

It seems like other developers are able to work around this from within the a docker container. This doesn't seem like a blocker or technical limitation due to using containers.

In google's oauth doc: https://developers.google.com/identity/protocols/oauth2/web-server#python_1
You specify the webserver, so I am not sure why you are stating it is random. 

Unless I am looking at the wrong file, is this the location where you are specifying the random port? 
https://github.com/janeczku/calibre-web/blob/master/cps/services/gmail.py#L61

In which case, you could easily make this a static port - or if running in a container environment, specify a static port:
https://stackoverflow.com/questions/43878953/how-does-one-detect-if-one-is-running-within-a-docker-container-within-python/43879407

**Comment by kryndis** [comment]
So I was in a similar boat to @delize and I think I figured out a (very convoluted) workaround.

In my case, I'm running from a TrueNAS FreeBSD jail, but the symptoms of the problem were identical. My first clue came from noticing the text of a Google login page had been recorded in the nohup.out file. That's when I realized the server itself was trying to complete the authentication.

So, assuming you're running from an environment where you don't have (or want) a GUI and therefore don't have a graphical browser, here's how I got it to work. Note that you WILL need some sort of browser, text-based is fine. My jail had w3m available and working by default, so that's what I used.

1. Open a terminal to your server and launch calibre-web in the foreground with "python /path/to/cps.py"
2. On your normal machine, navigate to the mail settings and click the button. At this point it will appear to hang as always, but if you check your terminal, you should find a Google login page open in whatever browser is your default. Now if you could login here, life would be peachy, but unfortunately captchas and text browsers don't mix, so go ahead and quit out of the browser.
3. You should be presented with a very long Google authentication URL (this was what was just open in the text browser.) Go ahead and copy this into your browser on your desktop in a separate tab (make sure to leave the calibre-web page up) and you should be able to perform oauth authentication the same as usual.
4. At this point it will attempt to forward you to "http://localhost:<random_port>/<long_string_of_nonsense>" which obviously isn't going to work. No worries, go ahead and copy that URL.
5. Open a second terminal to your calibre-web server and open that URL you copied in a browser there. Note that if you're using w3m, it doesn't know how to deal with a URL without the http prefix that modern browsers like to use, so you'll need to add it.
6. You should see a simple "authentication successful" message on the browser in the second terminal and the hung calibre-web page will suddenly spring back to life with a properly working oauth setup!
7. At this point you can go ahead and kill the foregrounded calibre-web server process and restart it the way you normally would. You should be all set!

I'd be curious if this method works for anyone else that has a similar problem.

I think what I've done here is more or less invented a bastardized version of the run_console strategy found here: https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html by subverting the run_local_server strategy that is currently used in calibre-web. Not sure if it would be worth it to someone to look into adding official support for a run_console strategy or not.

**Comment by rubenlagus** [comment]
Kudos @kryndis , that helped a lot. 

Steps I followed were similar to yours but I don't have an browser, I managed just to use CURL for it and worked:

`curl "http://localhost:XXXXX/?state=YYYYYYYY&scope=email%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/gmail.send&authuser=0&prompt=consent"`

**Comment by henkisdabro** [comment]
Is there a working solution for us running the docker-container version? I can't understand @kryndis steps above (how i would run the python command, in the foreground, within a docker container)

**Comment by Orgjvr** [comment]
@henkisdabro  Here is what I did to get my docker container working:
1. Follow this procedure to create an oauth token: https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail 
2. Add above result file to docker app with -v /app/calibre-web/gmail.json:/mnt/user/appdata/calibre-web/gmail.json (change paths as needed)
3. Inside docker app: get PID of current calibre app: `ps -C "python3 /app/calibre-web/cps.py" -o pid=`
5.  Run the following command to kill the current calibre-web and restart it to get realtime output in terminal: `kill `PID FROM STEP ` && python3 /app/calibre-web/cps.py`
6. Click on  "Setup gmail account as email server" button in Calibre-Web
7. Copy link in terminal and open in any browser. Follow prompts and Allow access.
8. Copy failure link from browser and paste in docker container: `curl "LOCALHOST LINK FROM BROWSER"` Keep the double quotes around the link.
9. Thats it. Now you can exit and restart your container and test it.

Hope it helps.

**Comment by henkisdabro** [comment]
Thanks @Orgjvr very much for the detailed steps and full commands, so helpful for us newbies! This worked really well and email sending is now working!

**Comment by delize** [comment]
Can confirm that this is a solution to the original issue. :) 

Really appreciate everyone coming together here to help us on Docker. :)

**Comment by IHSten** [comment]
Really helpful @Orgjvr thank you! Only thing I found to do differently is for step 4, use the command

`kill PID && python3 /app/calibre-web/cps.py &`

So you can keep the same shell while still getting terminal output and do the full authentication flow without opening another shell into the docker container, seemed to make it a lot smoother for me. Thanks again!

**Comment by Plaidstallion** [comment]
> @henkisdabro Here is what I did to get my docker container working:
> 
> 1. Follow this procedure to create an oauth token: https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail
> 2. Add above result file to docker app with -v /app/calibre-web/gmail.json:/mnt/user/appdata/calibre-web/gmail.json (change paths as needed)
> 3. Inside docker app: get PID of current calibre app: `ps -C "python3 /app/calibre-web/cps.py" -o pid=`
> 4. Run the following command to kill the current calibre-web and restart it to get realtime output in terminal: `kill `PID FROM STEP ` && python3 /app/calibre-web/cps.py`
> 5. Click on  "Setup gmail account as email server" button in Calibre-Web
> 6. Copy link in terminal and open in any browser. Follow prompts and Allow access.
> 7. Copy failure link from browser and paste in docker container: `curl "LOCALHOST LINK FROM BROWSER"` Keep the double quotes around the link.
> 8. Thats it. Now you can exit and restart your container and test it.
> 
> Hope it helps.

How would I do this in the linuxserver.io container? It has s6-supervise monitoring the process and it immediately restarts cps.py.

**Comment by dr400** [comment]
Thx guys for the great job ... BUT : on step 4, application keeps on restarting by itself (port 8083 is already in use ...). Terminla won't show realtime output. Any idea ?

**Comment by Plaidstallion** [comment]
> 

So make sure you are not running two different commands for `kill <pid_number> && python3 /app/calibre-web/cps.py`. Enusre you run it as one command with the && in between.

If you run those two commands separately s6-supervise will restart it in the linuxserver.io container before you can manually restart it.

**Comment by Plaidstallion** [comment]
> Thx guys for the great job ... BUT : on step 4, application keeps on restarting by itself (port 8083 is already in use ...). Terminla won't show realtime output. Any idea ?

So make sure you are not running two different commands for `kill <pid_number> && python3 /app/calibre-web/cps.py` Enusre you run it as one command with the `&&` in between.

If you run those two commands separately s6-supervise will restart it in the linuxserver.io container before you can manually restart it.

**Comment by dr400** [comment]
> > Thx guys for the great job ... BUT : on step 4, application keeps on restarting by itself (port 8083 is already in use ...). Terminla won't show realtime output. Any idea ?
> 
> So make sure you are not running two different commands for `kill <pid_number> && python3 /app/calibre-web/cps.py` Ensure you run it as one command with the `&&` in between.
> 
> If you run those two commands separately s6-supervise will restart it in the linuxserver.io container before you can manually restart it.

Done it that way ... nothing comes out into the terminal. Log is showing :

`2022-06-17T15:21:12.544899340Z Error starting server: [Errno 98] Address already in use: ('', 8083)
2022-06-17T15:21:18.109544367Z Error starting server: [Errno 98] Address already in use: ('', 8083)
2022-06-17T15:21:23.663564926Z Error starting server: [Errno 98] Address already in use: ('', 8083)
2022-06-17T15:21:29.208855181Z Error starting server: [Errno 98] Address already in use: ('', 8083)
2022-06-17T15:21:35.016975544Z Error starting server: [Errno 98] Address already in use: ('', 8`

**Comment by dr400** [comment]
Sorry to insist but any help is more than welcome. My system is docker with calibre-web latest image. When open, the terminal will show nothing on calibre-web gmail provider information button press. All processes on google side are done. Last but not least, before all this, clicking the Oauth2 button was not freezing the application, but pressing the button below ("configuration of gmail account for mail server") fails and says : "no valid gmail.json files with Oauth information found"). Hope this helps a bit further ... Help is appreciated here ...

**Comment by Orgjvr** [comment]
> Sorry to insist but any help is more than welcome. My system is docker with calibre-web latest image. When open, the terminal will show nothing on calibre-web gmail provider information button press. All processes on google side are done. Last but not least, before all this, clicking the Oauth2 button was not freezing the application, but pressing the button below ("configuration of gmail account for mail server") fails and says : "no valid gmail.json files with Oauth information found"). Hope this helps a bit further ... Help is appreciated here ...

@dr400 I think you might have an error in step 2. Either the volume was not added correctly to the docker container, or the files does not exists in the mounted path. 

Take note that in step 2 the parameters to the -v are 2 paths which are separated by a colon.  The first one needs to be the same as in step 2, while the second path needs to point to the file on your host system. In other words, you need to be able to do "ls /app/calibre-web/gmail.json" inside the docker container, and also need to be able to "ls /mnt/user/appdata/calibre-web/gmail.json" outside your container on the host system. This second path might be different for you. It would depend on where you saved the gmail.json file. Just make sure that you use the path where you saved your file, as the path after the colon in step 2.

Hope it helps.

**Comment by dr400** [comment]
> @dr400 I think you might have an error in step 2. Either the volume was not added correctly to the docker container, or the files does not exists in the mounted path.
> 
> Take note that in step 2 the parameters to the -v are 2 paths which are separated by a colon. The first one needs to be the same as in step 2, while the second path needs to point to the file on your host system. In other words, you need to be able to do "ls /app/calibre-web/gmail.json" inside the docker container, and also need to be able to "ls /mnt/user/appdata/calibre-web/gmail.json" outside your container on the host system. This second path might be different for you. It would depend on where you saved the gmail.json file. Just make sure that you use the path where you saved your file, as the path after the colon in step 2.
> 
> Hope it helps.

Hi Orgjvr and thanks for helping.

Here below is the docker command I use : 

docker run --name=calibre-web1 -e PUID=1026 -e PGID=100 -e TZ=Europe/Paris -e DOCKER_MODS=linuxserver/calibre-web:calibre -e OAUTHLIB_RELAX_TOKEN_SCOPE=1 -p 8081:8083 -v /volume1/docker/calibre-web:/config -v /volume1/docker/calibre/Calibre_Library/Calibre_Library:/books -v /volume1/docker/Localtime/localtime:/etc/localtime -v /volume1/docker/calibre-web/gmail.json:/mnt/user/appdata/calibre-web/gmail.json --restart unless-stopped lscr.io/linuxserver/calibre-web:latest

Mount is correct. Both ways are available.
Can't figure out what is wrong ...

**Comment by dr400** [comment]
> > Thanks for the quick reply but it is the way I've done it ... but still nothing comes out into the terminal with regards to steps 5 & 6 Log is showing :
> > `2022-06-17T15:21:12.544899340Z Error starting server: [Errno 98] Address already in use: ('', 8083) 2022-06-17T15:21:18.109544367Z Error starting server: [Errno 98] Address already in use: ('', 8083) 2022-06-17T15:21:23.663564926Z Error starting server: [Errno 98] Address already in use: ('', 8083) 2022-06-17T15:21:29.208855181Z Error starting server: [Errno 98] Address already in use: ('', 8083) 2022-06-17T15:21:35.016975544Z Error starting server: [Errno 98] Address already in use: ('', 8`
> > ![image](https://user-images.githubusercontent.com/48514024/174330987-38c1a71a-a270-4678-98d7-714112163d9d.png)
> 
> Same issue is occurring for me even if using the build from around the time the original solution was posted. I don't know if this helps narrow down the problem but I am running this on arm64 (raspberry pi).

looks like you may run into the same trouble ... in your docker compose, mnt wherever you're gmail.json is into /app/calibre-web/gmail.json : 

-v /volume1/docker/calibre-web/gmail.json:/app/calibre-web/gmail.json

instead of 

-v /volume1/docker/calibre-web/gmail.json:/mnt/usr/appdata/calibre-web/gmail.json 

Hope this helps

**Comment by Plaidstallion** [comment]
The problem that I am having now is that with the linuxserver.io container, every week or so the access stops working and the books fail to send. I have to redo the entire process and then the send feature begins working for a time. Has anyone else experienced this problem? If so, have you found a fix?

**Comment by IHSten** [comment]
> The problem that I am having now is that with the linuxserver.io container, every week or so the access stops working and the books fail to send. I have to redo the entire process and then the send feature begins working for a time. Has anyone else experienced this problem? If so, have you found a fix?

I experienced this as well and am hoping that I've fixed it by "publishing" my google cloud application. By default, applications that are in the "testing" state only have valid credentials for 7 days. You can "publish" without verifying, you'll just get an extra warning screen in the OAuth flow.

**Comment by Plaidstallion** [comment]
> > The problem that I am having now is that with the linuxserver.io container, every week or so the access stops working and the books fail to send. I have to redo the entire process and then the send feature begins working for a time. Has anyone else experienced this problem? If so, have you found a fix?
> 
> I experienced this as well and am hoping that I've fixed it by "publishing" my google cloud application. By default, applications that are in the "testing" state only have valid credentials for 7 days. You can "publish" without verifying, you'll just get an extra warning screen in the OAuth flow. Hopefully I'll remember to update this post if it works or not in a week.

Thanks so much for the response. I just published and set up auth again based on your advice. Fingers crossed it solves the issue.

**Comment by naronick** [comment]
I've run into a new issue on this one - previously the instructions by [Orgjvr](https://github.com/Orgjvr) worked just fine and got me up and running. I ran into the same one week expiration that [Plaidstallion](https://github.com/Plaidstallion) and [IHSten](https://github.com/IHSten) had, but now when I try to reauthorize the google oauth page gives me the following error: 
Error 400: redirect_uri_mismatch
with explanation
redirect_uri: http://localhost:44115/

I've added "http://localhost" to my allowed redirect URIs, but no that's not working either. 

Anyone have a similar issue and able to get around it?

**Comment by sheldon-es-MRM** [comment]
> @henkisdabro Here is what I did to get my docker container working:
> 
> 1. Follow this procedure to create an oauth token: https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail
> 2. Add above result file to docker app with -v /app/calibre-web/gmail.json:/mnt/user/appdata/calibre-web/gmail.json (change paths as needed)
> 3. Inside docker app: get PID of current calibre app: `ps -C "python3 /app/calibre-web/cps.py" -o pid=`
> 4. Run the following command to kill the current calibre-web and restart it to get realtime output in terminal: `kill `PID FROM STEP ` && python3 /app/calibre-web/cps.py`
> 5. Click on  "Setup gmail account as email server" button in Calibre-Web
> 6. Copy link in terminal and open in any browser. Follow prompts and Allow access.
> 7. Copy failure link from browser and paste in docker container: `curl "LOCALHOST LINK FROM BROWSER"` Keep the double quotes around the link.
> 8. Thats it. Now you can exit and restart your container and test it.
> 
> Hope it helps.

Thanks, it worked for me. I've calibre-web installed in a Raspberry and had the same problem. I only had to change the cps route.

**Comment by DarrenYOW** [comment]
Thanks! Worked perfectly for me.

**Comment by CultusMechanicus** [comment]
Just as an FYI, on the linuxserver.io docker image I had to do: `export CALIBRE_DBPATH=/config` in the docker container before the `kill`, otherwise it didn't actually use my existing config.

**Comment by Plaidstallion** [comment]
Also, I recently found out you can use app codes with gmail to achieve the same functionality we had with simple auth before. After setting up a 2FA device one time it will give you essentially a username and password to send emails from the account with https://ugtechmag.com/enable-basic-authentication-gmail-account/

**Comment by CultusMechanicus** [comment]
> Also, I recently found out you can use app codes with gmail to achieve the same functionality we had with simple auth before. After setting up a 2FA device one time it will give you essentially a username and password to send emails from the account with.
> 
> https://ugtechmag.com/enable-basic-authentication-gmail-account/
> 
> https://support.google.com/mail/answer/185833?hl=en

I couldn't get that to work, I set up an app password and set the server as smtp.gmail.com, TLS, port 527 etc but email tasks just ran forever and never set anything. They didn't out right fail, but they didn't work either.

**Comment by Plaidstallion** [comment]
> I couldn't get that to work, I set up an app password and set the server as smtp.gmail.com, TLS, port 527 etc but email tasks just ran forever and never set anything. They didn't out right fail, but they didn't work either.

Interesting, ok. I guess as I have mail send working with Google OAuth, I won't mess with it. I was able to use app codes for other services but it seems not to be an option here. Thanks for the info.

**Comment by DarrenYOW** [comment]
Actually, that's what I did in the end.

After my "temp" OAuth expired, I wasn't able to get it to work again with a regenerated token, so I replaced it with SMTP using the app code.

Been working fine, so I'm not touching it.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by frizat82** [comment]
@DarrenYOW  same issues i'm having - what SMTP service do you use?  I'd prefer to move off the gmail token anyway it's a hassle

**Comment by Plaidstallion** [comment]
> @DarrenYOW same issues i'm having - what SMTP service do you use? I'd prefer to move off the gmail token anyway it's a hassle

It's a bit of a pain to setup but I use AmazonSES for some other services that didn't have options for oath.

**Comment by DarrenYOW** [comment]
I'm using Gmail, as I already had the app password/token set up for other containers. Not ideal, but it is working for now. I don't anticipate hitting the send/attachment limit. Added to the "sh#t I gotta fix later" pile.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by rickfmn** [comment]
I have the gmail.json placed at /app/calibre-web/gmail.json.
I can terminal in and cat the file fine, however I just get this note in the logs:
[2023-07-10 21:21:07,666] ERROR {cps.admin:1289} Found no valid gmail.json file with OAuth information

I updated my copy of gmail.py to return the full path of the gmail.json file being requested and found it was looking for it at:
/config/gmail.json

So perhaps this comment may help someone else trying to configure this and failing.

**Comment by rickfmn** [comment]
Ok still running into issues here.. I have the gmail.json loading, I have then done these steps:

- Export config: export CALIBRE_DBPATH=/config
- get service id: ps -C "python3 /app/calibre-web/cps.py" -o pid=
- Kill and Start CPS again: kill [PID] && python3 /app/calibre-web/cps.py &
- Clicked the Setup Gmail button, gotten the URL from the terminal, pasted into new browser.
- That allows me to log in and click allow, however after that I am presented with a URL back to localhost on a non-opened port.  I think this step is needed to finish the config.  I have tried to change the port to match 8083 (or whatever port calibre-web is on), but it just spins.

What am I missing?

**Comment by kaibagley** [comment]
> -- FIXED -- Ok still running into issues here.. I have the gmail.json loading, I have then done these steps:
> 
>     * Export config: export CALIBRE_DBPATH=/config
> 
>     * get service id: ps -C "python3 /app/calibre-web/cps.py" -o pid=
> 
>     * Kill and Start CPS again: kill [PID] && python3 /app/calibre-web/cps.py &
> 
>     * Clicked the Setup Gmail button, gotten the URL from the terminal, pasted into new browser.
> 
>     * That allows me to log in and click allow, however after that I am presented with a URL back to localhost on a non-opened port.  I think this step is needed to finish the config.  I have tried to change the port to match 8083 (or whatever port calibre-web is on), but it just spins.
> 
> 
> What am I missing? -- EDIT
> 
> I missed the last step
> 
>     * curl "localhost address"
> 
> 
> Working now (at least for now)

Can confirm this works, as long as the gmail.json is in /config, rather than /mnt/...

**Comment by NotAGizzard** [comment]
hey guys i was and still am having an issue with calibre web saying it found no valid gmail.json file with oauth information. i have followed all of the steps for setting up a mail server including the docker steps. i also have the oauth file from google downloaded and bound (at least I'm pretty sure its bound, I'm using portainer to manage my containers) to /app/calibre-web/gmail.json.

**Comment by jt196** [comment]
> hey guys i was and still am having an issue with calibre web saying it found no valid gmail.json file with oauth information. i have followed all of the steps for setting up a mail server including the docker steps. i also have the oauth file from google downloaded and bound (at least I'm pretty sure its bound, I'm using portainer to manage my containers) to /app/calibre-web/gmail.json.

Not to harp on about it but try the app-specific approach I outlined above. Much simpler and is working on my setup.

**Comment by SercanKaraoglu** [comment]
> I've run into a new issue on this one - previously the instructions by [Orgjvr](https://github.com/Orgjvr) worked just fine and got me up and running. I ran into the same one week expiration that [Plaidstallion](https://github.com/Plaidstallion) and [IHSten](https://github.com/IHSten) had, but now when I try to reauthorize the google oauth page gives me the following error: Error 400: redirect_uri_mismatch with explanation redirect_uri: http://localhost:44115/
> 
> I've added "http://localhost" to my allowed redirect URIs, but no that's not working either.
> 
> Anyone have a similar issue and able to get around it?

Google app type should be Desktop app not web server . Change that and it should work

**Comment by delize** [comment]
@OzzieIsaacs / /@janeczku 

Has this process been improved at all? 

Google has mentioned that they are deprecating several methods of email that do not use oAuth - so oAuth is going to be a preferred route in the future, and as I am setting this up again from scratch - this is becoming a struggle with the latest image and the most recent oAuth instructions found in this issue.

**Comment by latipun7** [comment]
> I've run into a new issue on this one - previously the instructions by [Orgjvr](https://github.com/Orgjvr) worked just fine and got me up and running. I ran into the same one week expiration that [Plaidstallion](https://github.com/Plaidstallion) and [IHSten](https://github.com/IHSten) had, but now when I try to reauthorize the google oauth page gives me the following error: Error 400: redirect_uri_mismatch with explanation redirect_uri: [http://localhost:44115](http://localhost:44115/)
> 
> I've added "http://localhost" to my allowed redirect URIs, but no that's not working either.
> 
> Anyone have a similar issue and able to get around it?

I had same issue with @naronick in https://github.com/janeczku/calibre-web/issues/2254#issuecomment-1224284416. Any solution or explanation? Thank you.

**Comment by wisie** [comment]
> export CALIBRE_DBPATH=/config && kill 355 && python3 /app/calibre-web/cps.py &

This did the trick for me. Thank you.

**Comment by latipun7** [comment]
>     1. Follow this procedure to create an oauth token: [Wiki: Setup Mailserver (Gmail)](https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail)
> 
>     2. Add above result file to docker app with -v /app/calibre-web/gmail.json:/mnt/user/appdata/calibre-web/gmail.json (change paths as needed)
> 
>     3. Inside docker app: get PID of current calibre app: `ps -C "python3 /app/calibre-web/cps.py" -o pid=`
> 
>     4. Run the following command to kill the current calibre-web and restart it to get realtime output in terminal: `kill `PID FROM STEP ` && python3 /app/calibre-web/cps.py`
> 
>     5. Click on  "Setup gmail account as email server" button in Calibre-Web
> 
>     6. Copy link in terminal and open in any browser. Follow prompts and Allow access.
> 
>     7. Copy failure link from browser and paste in docker container: `curl "LOCALHOST LINK FROM BROWSER"` Keep the double quotes around the link.
> 
>     8. Thats it. Now you can exit and restart your container and test it.
> 
> 
> Hope it helps.

I tried following steps from @Orgjvr but encountered error on step 7.5.

After I run `curl`, the terminal did give me `The authentication flow has completed. You may close this window.`
But, on calibre-web page, returned this message instead of success: `(mismatching_state) CSRF Warning! State not equal in request and response.`
![image](https://github.com/janeczku/calibre-web/assets/20012970/00f7c8eb-20d4-4800-b3c3-fc4b45b36336)
How to resolve that problem?

### Here's my step to reproduce:
- my linux server at 192.168.1.1, run `~/calibre-web/bin/cps &` via ssh terminal from my laptop (my calibre-web installed with pip)
- access calibre-web (http://192.168.1.1:8083) from my laptop's browser at 192.168.1.2
- run step 5-7 above, curl from ssh terminal
- page refreshed and got CSRF error.
- trying to send email or access register page, saying email server not setup.
![image](https://github.com/janeczku/calibre-web/assets/20012970/6e2efa70-6d0b-410f-8a4b-fe5eb7026ce7)

**Comment by delize** [comment]
@OzzieIsaacs has this been fixed in the gui to natively work yet?

**Comment by OzzieIsaacs** [comment]
It‘s a docker only problem

**Comment by chen8160** [comment]
Following the steps here and got "could not locate runnable browser " in the calibre-web UI and no links in the terminal which I ran the `export CALIBRE_DBPATH=/config && kill [pid] && python3 /app/calibre-web/cps.py &`.

Any idea why this is happening?

**Comment by thankarezos** [comment]
> Following the steps here and got "could not locate runnable browser " in the calibre-web UI and no links in the terminal which I ran the `export CALIBRE_DBPATH=/config && kill [pid] && python3 /app/calibre-web/cps.py &`.
> 
> Any idea why this is happening?

I am gettomg the same error using linux.io server docker image

**Comment by ofostier** [comment]
Same problem for me using linux.io image
url doesn't happend in the terminal 
it is like 2 process run at the same time

**Comment by Akadiuss** [comment]
> Following the steps here and got "could not locate runnable browser " in the calibre-web UI and no links in the terminal which I ran the `export CALIBRE_DBPATH=/config && kill [pid] && python3 /app/calibre-web/cps.py &`.
> 
> Any idea why this is happening?

I have been looking for hours now, same errors and I'm not getting the link.

**Comment by tamuseanmiller** [comment]
Same issue here, would love to reopen this as it seems to be a regression or something.

**Comment by sargunv** [comment]
I also got "could not locate runnable browser" and resolved it with `apt install lynx` in the container. I didn't actually use lynx; just needed it present to get past that error and set up gmail auth with the usual `export CALIBRE_DBPATH=/config && kill [pid] && python3 /app/calibre-web/cps.py`

**Comment by math-eww** [comment]
Hey all - just went through the docker setup myself and got it working (thanks to all in this thread!) and wanted to share a simple clear way to get going

I set up a browser intercept so we don't need to install lynx (which has some issues with JS in the google auth flow) - this will just print the url you need to open directly

```
# Set up browser intercept
echo -e '#!/bin/bash\necho "Browser open attempt with URL: \$1" >> /tmp/oauth_url_log.txt\necho "Open the following URL manually in a browser:"\necho \$1' > /usr/local/bin/log_browser.sh && chmod +x /usr/local/bin/log_browser.sh
export BROWSER="/usr/local/bin/log_browser.sh"

# Get PID
ps -C "python3 /app/calibre-web/cps.py" -o pid=

# Set env, kill using PID from previous step, and relaunch calibre
export CALIBRE_DBPATH=/config && kill [PID]  && python3 /app/calibre-web/cps.py

# Click the setup gmail button in webui, a 'browser' will be opened with the OAuth authorization URL - instead we will print it to console

# Open the link in any browser, go through the login flow
# - Make sure to tick the send email permission if its not ticked

# The last step will fail in your browser (redirect to localhost) - copy that URL and place it in the curl command below
# - Use a second shell to do this (open a new docker exec) as the first one is still running calibre
curl "LOCALHOST LINK FROM BROWSER"
```

**Comment by stayupthetree** [comment]
> export CALIBRE_DBPATH=/config && kill [PID]  && python3 /app/calibre-web/cps.py

You are the real MVP, this worked brilliantly

**Comment by mitch-e** [comment]
Hi All,

After a lot of digging and running through everyone's solutions (each has gotten me one step further each time, thank you!) , I found I needed to completely stop the Calibre Web service from being restarted by S6-Supervise. 

It was just restarting way too quick even if I linked the KILL command along with a fresh Calibre-Web instance straight away. (Not sure if this method has been mentioned up above, apologies if it already has).


To get mine working, I needed to do the following:

- Setup gmail.json as described in the main instructions and copy it to the /config directory.

- Enter calibre-web container

- Stop the Calibre-Web service using S6-svc (will also stop it from restarting):

	`cd /var/run/service && s6-svc -D svc-calibre-web`

- Set up browser intercept (run each command separately):
	`echo -e '#!/bin/bash\necho "Browser open attempt with URL: \$1" >> /tmp/oauth_url_log.txt\necho "Open the following URL manually in a browser:"\necho \$1' > /usr/local/bin/log_browser.sh && chmod +x 	/usr/local/bin/log_browser.sh`

	`export BROWSER="/usr/local/bin/log_browser.sh"`

- Check if the Calibre Web process is running (Will return a PID if running, It shouldn't be running):
	`ps -C "python3 /app/calibre-web/cps.py" -o pid=`

- Export the Calibre-Web settigs and start a copy of Calibre-Web which should show terminal output:
	`export CALIBRE_DBPATH=/config && FLASK_DEBUG=true && python3 -u /app/calibre-web/cps.py &`

- Click on "Setup gmail account as email server" button in Calibre-Web.

- Authorisation URL should appear - If the Auth URL does not show up, try checking the calibre-web.log file to see if URL pops up in there.

- Copy link in terminal and open in any browser. Follow prompts and Allow access. The last step will fail in your browser (redirect to localhost) - copy that URL and place it in the curl command below: curl "LOCALHOST LINK FROM BROWSER" Keep the double quotes around the link.

	`curl "LOCALHOST LINK FROM BROWSER"`

	The authentication flow has completed. You may close this window.


- Delete the down file from the s6 services directory (allows Calibre-Web to restart when the container comes back up):
	`rm /var/run/service/svc-calibre-web/down`


- Restart the container

Hopefully this helps anyone finding themselves in the exact same situation I was in.

**Comment by gregbert42** [comment]
> Hi All,
> 
> After a lot of digging and running through everyone's solutions (each has gotten me one step further each time, thank you!) , I found I needed to completely stop the Calibre Web service from being restarted by S6-Supervise.
> 
> It was just restarting way too quick even if I linked the KILL command along with a fresh Calibre-Web instance straight away. (Not sure if this method has been mentioned up above, apologies if it already has).
> 
> To get mine working, I needed to do the following:
> 
> * Setup gmail.json as described in the main instructions
> * Enter calibre-web container
> * Stop the Calibre-Web service using S6-svc (will also stop it from restarting):
>   `cd /var/run/service && s6-svc -D svc-calibre-web`
> * Set up browser intercept (run each command separately):
>   `echo -e '#!/bin/bash\necho "Browser open attempt with URL: \$1" >> /tmp/oauth_url_log.txt\necho "Open the following URL manually in a browser:"\necho \$1' > /usr/local/bin/log_browser.sh && chmod +x 	/usr/local/bin/log_browser.sh`
>   `export BROWSER="/usr/local/bin/log_browser.sh"`
> * Check if the Calibre Web process is running (Will return a PID if running, It shouldn't be running):
>   `ps -C "python3 /app/calibre-web/cps.py" -o pid=`
> * Export the Calibre-Web settigs and start a copy of Calibre-Web which should show terminal output:
>   `export CALIBRE_DBPATH=/config && FLASK_DEBUG=true && python3 -u /app/calibre-web/cps.py &`
> * Click on "Setup gmail account as email server" button in Calibre-Web.
> * Authorisation URL should appear - If the Auth URL does not show up, try checking the calibre-web.log file to see if URL pops up in there.
> * Copy link in terminal and open in any browser. Follow prompts and Allow access. The last step will fail in your browser (redirect to localhost) - copy that URL and place it in the curl command below: curl "LOCALHOST " Keep the double quotes around the link.
>   `curl "LOCALHOST <LINK FROM BROWSER>"`
>   The authentication flow has completed. You may close this window.
> * Delete the down file from the s6 services directory (allows Calibre-Web to restart when the container comes back up):
>   `rm /var/run/service/svc-calibre-web/down`
> * Restart the container
> 
> Hopefully this helps anyone finding themselves in the exact same situation I was in.

Oh my god. How the heck did you figure this out? It worked for me too! But wow...

**Comment by mischavandenburg** [comment]
Thanks to @gregbert42 I finally got it to work with a small adjustment:

`export CALIBRE_DBPATH=/config && export FLASK_DEBUG=true && python3 -u /app/calibre-web/cps.py`

Added a second export for the env var and I did not send the process to the background with &

Also, I had to copy my gmail.json to /config , for CWA I had it in /app/calibre-web/

**Comment by gregbert42** [comment]
> Thanks to [@gregbert42](https://github.com/gregbert42) I finally got it to work with a small adjustment:
> 
> `export CALIBRE_DBPATH=/config && export FLASK_DEBUG=true && python3 -u /app/calibre-web/cps.py`
> 
> Added a second export for the env var and I did not send the process to the background with &
> 
> Also, I had to copy my gmail.json to /config , for CWA I had it in /app/calibre-web/

All credit to @mitch-e and the folks that were sources for them

**Comment by mitch-e** [comment]
> > Thanks to [@gregbert42](https://github.com/gregbert42) I finally got it to work with a small adjustment:
> > `export CALIBRE_DBPATH=/config && export FLASK_DEBUG=true && python3 -u /app/calibre-web/cps.py`
> > Added a second export for the env var and I did not send the process to the background with &
> > Also, I had to copy my gmail.json to /config , for CWA I had it in /app/calibre-web/
> 
> All credit to [@mitch-e](https://github.com/mitch-e) and the folks that were sources for them

@gregbert42 , thank you but all good, just glad it's saving people hours of troubleshooting time!

**Comment by jshank** [comment]
This is the closest I've been but the browser just spins after hitting **Continue** in the `Calibre-web wants access to your Google Account` screen. I don't know what the `<LINK FROM BROWSER>` from `curl "LOCALHOST <LINK FROM BROWSER>"` is supposed to be. I've tried using `curl "LOCALHOST https://accounts.google.com/signin/oauth/v2/consentsummary?as=<redacted>" but just end up getting error `curl: (3) URL rejected: Malformed input to a URL function`

**Comment by mitch-e** [comment]
Hi @jshank,

Please have a look at my instructions and not any of the quotes.

Reason is because I stuffed up my curl command and edited my post to fix it up.

Please just enter:
`curl “URLFromBrowser”`

That should fix your URL issues!

Cheers,
Mitch-e

**Comment by jshank** [comment]
@mitch-e thanks for the super quick reply and instructions. 

> Please just enter: `curl “URLFromBrowser”`

Everything works until I hit Continue in the Google authorization screen but no localhost type of url is returned, failed or otherwise. 

I did try `curl "https://accounts.google.com/signin/oauth/v2/consentsummary?as=<redacted>"` (the original URL that the terminal spits out) but I don't think that's the link I am supposed to get. I never get the failed redirect, the Chrome tab just spins after I hit Continue and doesn't ever time out or fail in a redirect.

**Comment by mitch-e** [comment]
@jshank ,

Odd, it should really look something like the below:

`http://localhost:57487/?state=<redacted>&code=<redacted>&scope=email%20https://www.googleapis.com/auth/gmail.send%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent`

If it is not coming up like that, you might need to re-do the creation of the gmail.json file like in [GMail setup instructions from the Devs](https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail) ?

**Comment by mitch-e** [comment]
> [@mitch-e](https://github.com/mitch-e) thanks for the super quick reply and instructions.
> 
> > Please just enter: `curl “URLFromBrowser”`
> 
> Everything works until I hit Continue in the Google authorization screen but no localhost type of url is returned, failed or otherwise.
> 
> I did try `curl "https://accounts.google.com/signin/oauth/v2/consentsummary?as=<redacted>"` (the original URL that the terminal spits out) but I don't think that's the link I am supposed to get. I never get the failed redirect, the Chrome tab just spins after I hit Continue and doesn't ever time out or fail in a redirect.

To make sure, you mean it is not showing up anywhere on the page or even in the address bar at the top of your internet browser?

What should happen is, after you have entered your credentials and accepted the Authorised access, your web browser should try and open the link beginning with "http://localhost:xxxx" and fail.

**Comment by jshank** [comment]
I fully deleted the project and then recreated it and it works. The instructions from https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail aren't quite aligned with the current version of the Google Cloud Console but I must have clicked something different this time. Thanks for the additional push! 

Now hoping the credential sticks around!

**Comment by mitch-e** [comment]
> I fully deleted the project and then recreated it and it works. The instructions from https://github.com/janeczku/calibre-web/wiki/Setup-Mailserver#Gmail aren't quite aligned with the current version of the Google Cloud Console but I must have clicked something different this time. Thanks for the additional push!
> 
> Now hoping the credential sticks around!

If the Authorization disappears after a week, try this [Issue 3305](https://github.com/janeczku/calibre-web/issues/3305#issuecomment-2655787013), I ended up having to do this to make sure it stuck around.

**Comment by mischavandenburg** [comment]
@mitch-e thanks again buddy it expired for me too, I published the app now.

**Comment by flywithdragons** [comment]
My app was working without issues in the past (after I set up a browser interrupt). Then when I logged in a few days ago, it wasn't working, i.e. emails were not going out. So I tried to get the Gmail activation done again. Unfortunately, now I get an error after the last step; i.e. after I submit the curl "URLfrombrowser". The error message is seen on the Calibre-web page on top (same screen where you hit the "Setup Gmail account" button. The error message on top says - 

**HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at <redacted>>: Failed to resolve 'oauth2.googleapis.com' ([Errno -3] Temporary failure in name resolution)"))**

For awareness, I was not getting this error two days ago; but the gmail wasn't working either. In the past, after submitting the curl command, the "Setup Gmail account" button would change to "Revoke Gmail Access". But it wouldn't do so this time; the page would remain on the original button. So I tried it a couple of times; in windows and in mac environment. Eventually, I started getting this "Max retries exceeded with url" error. 

Reading online on the error, some advised using a VPN. I tried that as well. Logged in via VPN to different cities to retry. However, I still get the same error. Would appreciate if anyone has any advice?

BTW - I also tried the "publish app" thing suggested a few posts back; same issue. I tried it via a different gmail account with a different json; same issue.

**Comment by jdwake** [comment]
> Hey all - just went through the docker setup myself and got it working (thanks to all in this thread!) and wanted to share a simple clear way to get going
> 
> I set up a browser intercept so we don't need to install lynx (which has some issues with JS in the google auth flow) - this will just print the url you need to open directly
> 
> ```
> # Set up browser intercept
> echo -e '#!/bin/bash\necho "Browser open attempt with URL: \$1" >> /tmp/oauth_url_log.txt\necho "Open the following URL manually in a browser:"\necho \$1' > /usr/local/bin/log_browser.sh && chmod +x /usr/local/bin/log_browser.sh
> export BROWSER="/usr/local/bin/log_browser.sh"
> 
> # Get PID
> ps -C "python3 /app/calibre-web/cps.py" -o pid=
> 
> # Set env, kill using PID from previous step, and relaunch calibre
> export CALIBRE_DBPATH=/config && kill [PID]  && python3 /app/calibre-web/cps.py
> 
> # Click the setup gmail button in webui, a 'browser' will be opened with the OAuth authorization URL - instead we will print it to console
> 
> # Open the link in any browser, go through the login flow
> # - Make sure to tick the send email permission if its not ticked
> 
> # The last step will fail in your browser (redirect to localhost) - copy that URL and place it in the curl command below
> # - Use a second shell to do this (open a new docker exec) as the first one is still running calibre
> curl "LOCALHOST LINK FROM BROWSER"
> ```

Just wanted to add that this solution worked great on a docker'ed [Calibre-Web-Automated](https://github.com/crocodilestick/Calibre-Web-Automated). Thank you [@math-eww] (https://github.com/math-eww)!

**Comment by Raytestrak** [comment]
> Hi All,
> 
> After a lot of digging and running through everyone's solutions (each has gotten me one step further each time, thank you!) , I found I needed to completely stop the Calibre Web service from being restarted by S6-Supervise.
> 
> It was just restarting way too quick even if I linked the KILL command along with a fresh Calibre-Web instance straight away. (Not sure if this method has been mentioned up above, apologies if it already has).
> 
> EDIT: This is for the Linuxserver.io docker container - https://hub.docker.com/r/linuxserver/calibre-web
> 
> [cut]
> 
> EDIT: If you are finding the OAuth token is resetting after a few days / week, try the following link, it's what I used to keep mine from acting up: [#3305 (comment)](https://github.com/janeczku/calibre-web/issues/3305#issuecomment-2655787013)

I'm also running the linuxserver image of calibre-web, but I'm having trouble getting is set up with these instructions. The authentication goes fine, I get the message that I can close this window, in Calibre-Web I see gmail set up succesfully and settings saved, but when I try to send a book, it says: Please configure the SMTP mail settings first...

What am I doing wrong? I have old SMTP settings that are invalid now, could those conflict?

**Comment by ggonmar** [comment]
Hm, am i the only one struggling with a bunch of 400 errors due to the auth redirect uri needing to have exactly the port that my calibre decided to use on that request?

I managed to reach the last step with the curl to the localhost url that google ended up giving, but after restarting the container, I am still not seeing the email server set up, and I'm back to step 1.... 

Can anyone help me, for the sake of the last 3 hours I've been fighting with this? 
Thanks!

**Comment by Sotyrs** [comment]
> Hm, am i the only one struggling with a bunch of 400 errors due to the auth redirect uri needing to have exactly the port that my calibre decided to use on that request?
> 
> I managed to reach the last step with the curl to the localhost url that google ended up giving, but after restarting the container, I am still not seeing the email server set up, and I'm back to step 1....
> 
> Can anyone help me, for the sake of the last 3 hours I've been fighting with this? Thanks!

Same issue here, haven't been able to solve it yet either.

**Comment by ggonmar** [comment]
Solved the problem regarding the localhost with the port: on the OAuth client generation, you need to select Desktop App instead of web app.

Howver, the method provided by @jdwake (and previously by @math-eww) is sadly still failing - after the final curl, calibre-web shows a banner with the message:

(missing_code) Missing code parameter in response.

So close yet so far!  Any last hints to solve this riddle? 
Thank you!

**Comment by brfpm** [comment]
> Solved the problem regarding the localhost with the port: on the OAuth client generation, you need to select Desktop App instead of web app.
> 
> Howver, the method provided by [@jdwake](https://github.com/jdwake) (and previously by [@math-eww](https://github.com/math-eww)) is sadly still failing - after the final curl, calibre-web shows a banner with the message:
> 
> (missing_code) Missing code parameter in response.
> 
> So close yet so far! Any last hints to solve this riddle? Thank you!

I'm having the same missing_code message. The method was working a few weeks ago. My token as expired and I'm trying to redo the process.

**Comment by ggonmar** [comment]
I gave up and went with the app password approach, easier and quicker than trying to commit to Oauth

**Comment by drizuid** [comment]
> EDIT: This is for the Linuxserver.io docker container - https://hub.docker.com/r/linuxserver/calibre-web

hi all, im the LSIO calibre-web maintainer, as mentioned by [Mitch-e](https://github.com/janeczku/calibre-web/issues/2254#issuecomment-2586060856), due to an upstream change in flask, prior instructions I provided [here](https://github.com/janeczku/calibre-web/issues/2254#issuecomment-1955185020) no longer work as CW checks for a default browser. **Mitch-e's method solves the issue elegantly** (though normally we wouldn't support users messing with s6, this is fine)  

> * rm /var/run/service/svc-calibre-web/down

though i will note that here, you can also just `s6-svc -U /var/run/service/svc-calibre-web` (which removes the down file and allows s6 to start the service)

**Comment by ardenzhan** [comment]
> Solved the problem regarding the localhost with the port: on the OAuth client generation, you need to select Desktop App instead of web app.
> 
> Howver, the method provided by [@jdwake](https://github.com/jdwake) (and previously by [@math-eww](https://github.com/math-eww)) is sadly still failing - after the final curl, calibre-web shows a banner with the message:
> 
> (missing_code) Missing code parameter in response.
> 
> So close yet so far! Any last hints to solve this riddle? Thank you!

Try quotes around the entire url for the final curl `curl "http://localhost ... prompt=consent"`. I got the same error as you before I quoted the url, but now it works! 😄

**Comment by PetoMasaryk** [comment]
Hello. I followed this procedure with success, i am able to send ebook to reader, but after 1-2 weeks, it will fail with error: token expired or revoked.
