### ISSUE TITLE
crashes on upload.

### ISSUE THREAD

**Issue by david85091** [janeczku/calibre-web#2394]
just upgraded to latest version and cannot upload  magazines. please help! ripping hair out!
tried rebooting restarting reconnect database etc. none work
i have over 1000 ebooks on this and have been using it for years. i love it! but this is a huge problem
a reload would be a nightmare

Internal Server Error

        
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
    
      
```        
Traceback (most recent call last):    
        
  File "C:\CWM\vendor\flask\app.py", line 2073, in wsgi_app   
    response = self.full_dispatch_request()
  File "C:\CWM\vendor\flask\app.py", line 1518, in full_dispatch_request    
    rv = self.handle_user_exception(e)
  File "C:\CWM\vendor\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\CWM\vendor\flask\app.py", line 1502, in dispatch_request       
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)    
  File "C:\CWM\cps\usermanagement.py", line 35, in decorated_view      
    return login_required(func)(*args, **kwargs)      
  File "C:\CWM\vendor\flask_login\utils.py", line 272, in decorated_view    
    return func(*args, **kwargs)     
  File "C:\CWM\cps\editbooks.py", line 59, in inner      
    return f(*args, **kwargs)    
  File "C:\CWM\cps\editbooks.py", line 1100, in upload     
    error = helper.update_dir_structure(book_id,   
  File "C:\CWM\cps\helper.py", line 685, in update_dir_structure      
    return update_dir_structure_file(book_id,  
  File "C:\CWM\cps\helper.py", line 488, in update_dir_structure_file   
    error = move_files_on_change(calibre_path,  
  File "C:\CWM\cps\helper.py", line 551, in move_files_on_change  
    os.makedirs(new_path)
  File "C:\Program Files\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Program Files\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
ValueError: mkdir: embedded null character in path
```
i also noticed i cant open books on shelves only under the books tab. i wish i had a backup before updating. what a mess!
update1:   its a problem with caliblur theme. uses standard and it works. however still cant upload.
update 2:   installed the windows version exe and moved the app.db to it and has same issue with uploading
[Calibre-Web-debug-pack.zip](https://github.com/janeczku/calibre-web/files/8621441/Calibre-Web-debug-pack.zip)

**Comment by OzzieIsaacs** [comment]
I have an idea, there is a problem is determine the filepath length it's using the wrong encoding, this leads to zeros in the string (this is what can be seen in the logfile: d\00o\00w\00n\00m\00a\00g\00a\00z\00.\00n\00e\00t\00.
Going back to version 0.6.17 and it should work, the app.db can be used for the older version. Calibre should be able to fix the metadata.db file (Library -> Library Maintenance -> Check Library or so)

**Comment by david85091** [comment]
i tried that and it didnt work.

**Comment by OzzieIsaacs** [comment]
What's not working?

**Comment by david85091** [comment]
using the app.db on 6.17

**Comment by OzzieIsaacs** [comment]
What wasn't working? Could you not log in????

**Comment by OzzieIsaacs** [comment]
Okay, please update to the newest nightly version: Admin section -> Basic configuration -> Server configuration -> Update Channel Nightly -> Save. Go back to admin section -> search for update -> perform update -> be happy.

(Tested on windows 10, I don't have a MACOS, but the line was saying produce the error for windows and MACOS, so I'm quite sure it will work afterwards)

**Comment by david85091** [comment]
Traceback (most recent call last):
  File "C:\CWM\cps.py", line 28, in <module>
    from cps.main import main
  File "C:\CWM\cps\__init__.py", line 29, in <module>
    from .MyLoginManager import MyLoginManager
  File "C:\CWM\cps\MyLoginManager.py", line 24, in <module>
    from flask_login import LoginManager
ModuleNotFoundError: No module named 'flask_login'
dead again.

**Comment by OzzieIsaacs** [comment]
No module named 'flask_login'
Please install flask_login -> `pip install flask_login` (in the right python version you are using)

**Comment by david85091** [comment]
the windows .exe version with the add.db from that mess when i change to nightly it says  unknown version  but on stable it shows the right one. i tried that flask login earlier and i had to install a few more and it still kept crashing

**Comment by OzzieIsaacs** [comment]
The windows exe should not have enabled the update process, so the update button should never show up.
You need the source version from the website.
Don't loose the app.db and keep a version from the beginning of your night mare

**Comment by david85091** [comment]
Traceback (most recent call last):
  File "C:\CWM\cps.py", line 28, in <module>
    from cps.main import main
  File "C:\CWM\cps\__init__.py", line 30, in <module>
    from flask_principal import Principal
ModuleNotFoundError: No module named 'flask_principal'

**Comment by david85091** [comment]
again thank you for your help

**Comment by OzzieIsaacs** [comment]
ModuleNotFoundError: No module named 'flask_principal' 
You need to install everything from the requirements.txt file like described in the readme

python3 -m pip install -r requirements.txt (executed from calibre-web root file)

Takes still 10min

**Comment by OzzieIsaacs** [comment]
Building the installer now

**Comment by david85091** [comment]
Running setup.py install for netifaces ... error
  error: subprocess-exited-with-error

  × Running setup.py install for netifaces did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running install
      running build
      running build_ext
      building 'netifaces' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> netifaces

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by OzzieIsaacs** [comment]
File is to big to upload 
2 min left

**Comment by OzzieIsaacs** [comment]
https://drive.google.com/file/d/1ZAnnSiWevpds3VYXIjrGNXw1Ke7RoCkK/view?usp=sharing

30MB

Please make a backup of the current installation, install the new one, copy the app.db in the folder and start it

**Comment by david85091** [comment]
apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
i am not sure what this error is.

**Comment by david85091** [comment]
OMG IT WORKS AGAIN!!!!!!!!! YOU ARE THE BEST I SO APPRECIATE IT I WAS SO SCARED I WOULD HAVE TO START FROM SCRATCH WITH OVER 1000 BOOKS!!!!!! TY TY TYis that other error gonna be a problem?

**Comment by david85091** [comment]
so whats better now? the exe version or the other way?

**Comment by OzzieIsaacs** [comment]
`PytzUsageWarning`
-> It's a warning
Not my fault. 
You can follow the discussion of the programmers  about it, (https://github.com/agronholm/apscheduler/discussions/570)

Or you ignore it

**Comment by david85091** [comment]
what about the 200mb upload 
problem with the other?

**Comment by OzzieIsaacs** [comment]
I created the exe because several people had problems with windows installations. I know from my past there have been some 
tricky things (lxml was one in the past). So to make it easier and lower the hurdles  created the exe version. 
The exe version has everything enabled, so it uses gevent, which doesn't have the 200MB upload limit

The obvious disadvantage of the exe is: If there is an error which is only fixed in the nightly version it's not possible for you to update.

**Comment by david85091** [comment]
ill take it. so it will still get the cover from a pdf without all the other stuff being installed?

**Comment by david85091** [comment]
i will guard the app.db with my life. LOL  small price to pay for everything included. again thank you very much and it is a great program. great job. i will be sending you a contribution. keep up the good work.

**Comment by OzzieIsaacs** [comment]
I‘d like to keep it open until the next release

**Comment by david85091** [comment]
sounds good i didnt know it would drop it from the board. newbe with github. sorry

**Comment by OzzieIsaacs** [comment]
Strange, to me it looks good. My paypal address is my email on my profile page

**Comment by david85091** [comment]
apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
<gevent._socket3.socket at 0x21d42d8dc00 object, fd=1516, family=2, type=1, proto=0>: Expected GET method: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr\r\n'
<gevent._socket3.socket at 0x21d42d8dc00 object, fd=1576, family=2, type=1, proto=0>: Expected GET method: '\x16\x03\x01\x00{\x01\x00\x00w\x03\x03H\x00*×.êÑfÜeP\x18SO\x10T\x8c]\x90í\x1be¼]\x08\x08±ígÀlº\x00\x00\x1aÀ/À+À\x11À\x07À\x13À\tÀ\x14À\n'
<gevent._socket3.socket at 0x21d4665ae00 object, fd=1644, family=2, type=1, proto=0>: Invalid http version: '\x16\x03\x01\x00î\x01\x00\x00ê\x03\x03±úî^Ldè\\\x9fÛ©¶\x02ÿzÞ¥Þ\x069¼Üµí\x7fÑioï\x1f\x0c\x95 Â@×¨±\x82D&$4ÏqÊ\n'
<gevent._socket3.socket at 0x21d45244a00 object, fd=1648, family=2, type=1, proto=0>: Invalid http version: 'PRI * HTTP/2.0\r\n'
<gevent._socket3.socket at 0x21d45244a00 object, fd=1648, family=2, type=1, proto=0>: Invalid http version: 'PRI * HTTP/2.0\r\n'
<gevent._socket3.socket at 0x21d43879060 object, fd=1644, family=2, type=1, proto=0>: Invalid HTTP method: 'hello'
<gevent._socket3.socket at 0x21d43879060 object, fd=1648, family=2, type=1, proto=0>: Expected GET method: 'éAaT\x03Uâ\x1cãcccccc-#\x81#;gïgC?cccc;cccccccccccccccccccccccccccccccccccczcccccccc\x9ccBcccc'
<gevent._socket3.socket at 0x21d43879060 object, fd=1644, family=2, type=1, proto=0>: Invalid HTTP method: '\x9eaQ[Q"?;\x077\x06(3V4\x18\x04,WR\r8S\x0f2\x080X1\x169\x14\x12$U"\x10\x00YV=aaaa\x89fË`aaYaaaaâX¤daaaa`~êiaaaaaab\x0cð\x0c\x0e»Quä\x9eë\x84.Ìµ§ß\x18\x14S@ôçm³#sd³Ì\x0b1\x05A!Ûñ5(IÍ²\x9f\x9a\r7\x08\n'
<gevent._socket3.socket at 0x21d43879060 object, fd=1648, family=2, type=1, proto=0>: Invalid HTTP method: 'hello'
<gevent._socket3.socket at 0x21d43879060 object, fd=1644, family=2, type=1, proto=0>: Invalid HTTP method: "§·\x08\x1bÿ$ÿ«ÿ\x00ÿaÿfö\x14½¯Hâ_5ÿ«ö\x0elåùÎ\x03V\x8c«>fð<³köÖ¸2&c\xadÒ\x9cø\xad\x8dsrP0SËh\\'\x1e^\x0cúw\x11VUoC\x1e|Î£ÓÆï§Ëºx+ì4\x9e\x81n\r²\x04ì\x06Zbï^\n"

gwtting all these wierd errors as the exe version runs.????

**Comment by OzzieIsaacs** [comment]
We talked already about the first line: https://github.com/janeczku/calibre-web/issues/2394#issuecomment-1117654024

The other ones are looking like invalid requests to your server:
- the 2nd last one (<gevent._socket3.socket at 0x21d43879060 object, fd=1648, family=2, type=1, proto=0>: Invalid HTTP method: 'hello') looks like a request to a email server
- This one is a  request with the new HTTP2 version, which isn't supported (<gevent._socket3.socket at 0x21d45244a00 object, fd=1648, family=2, type=1, proto=0>: Invalid http version: 'PRI * HTTP/2.0\r\n').

So nothing to worry about

**Comment by david85091** [comment]
its now causing the program to lock up. the site wont load till i go to the server bring up the dos box and hit enter. then it starts working again.

[2022-05-10 04:10:00,122]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-11 04:10:00 EDT)" (scheduled at 2022-05-10 04:10:00-04:00)
[2022-05-10 04:10:00,124]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-11 04:10:00 EDT)" executed successfully
[2022-05-11 04:10:00,012]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-12 04:10:00 EDT)" (scheduled at 2022-05-11 04:10:00-04:00)
[2022-05-11 04:10:00,012]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-12 04:10:00 EDT)" executed successfully
[2022-05-12 04:10:00,112]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-13 04:10:00 EDT)" (scheduled at 2022-05-12 04:10:00-04:00)
[2022-05-12 04:10:00,114]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-13 04:10:00 EDT)" executed successfully
[2022-05-13 04:10:00,077]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-14 04:10:00 EDT)" (scheduled at 2022-05-13 04:10:00-04:00)
[2022-05-13 04:10:00,080]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-14 04:10:00 EDT)" executed successfully
[2022-05-14 04:10:00,007]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-15 04:10:00 EDT)" (scheduled at 2022-05-14 04:10:00-04:00)
[2022-05-14 04:10:00,010]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2022-05-15 04:10:00 EDT)" executed successfully
