### ISSUE TITLE
Search error!! when fetching metadata

### ISSUE THREAD

**Issue by crazybadger** [janeczku/calibre-web#2562]
Hello!

I've started to see a 'Search error!!' message when trying to fetch metadata and I'm not sure why as it was working not too long ago.  I did find a similar issue from a Google search, but that was closed as it appeared to fix itself!  I did try clearing the browser cache and using a private window as recommended in that thread, but still the same.

**Steps to reproduce**
1. Select a book and click 'Edit Metadata'
2. Click 'Fetch Metadata'

**Logfile**
`[2022-10-05 19:07:09,291]  INFO {scholarly:95} Getting https://scholar.google.com/scholar?hl=en&q=Find%20Them%20Dead&as_vis=0&as_sdt=0,33
[2022-10-05 19:07:11,195]  WARN {cps.metadata_provider.douban:86} 403 Client Error: Forbidden for url: https://www.douban.com/j/search?cat=1001&q=Find%2BThem%2BDead
[2022-10-05 19:07:13,393] ERROR {cps:1457} Exception on /metadata/search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/calibre-web/cps/search_metadata.py", line 141, in metadata_search
    data.extend([asdict(x) for x in future.result() if x])
TypeError: 'NoneType' object is not iterable`

**Expected behaviour**
It would normally display a list of possible matches and allow one to be selected and the metadata updated

**Screenshots**
Attached, although not much to see!
![Screenshot 2022-10-05 at 19 10 24](https://user-images.githubusercontent.com/8318953/194133685-d0dfc0fa-c770-4c7f-9fbc-24b1a9da4ae6.jpg)

**Environment (please complete the following information):**
 - OS: TrueNAS Core 13.0-U2 running a ubuntu 20.04 VM and Docker 20.10.17
 - Python version: python3.8
 - Calibre-Web version: 0.6.19
 - Docker container: linuxserver/calibre-web:latest
 - Browser: Safari 16.1 (18614.2.7.1.1)

**Comment by fumarate** [comment]
I also met this issue

**Comment by jpbaril** [comment]
If I only select Amazon and Google as sources it works.

**Comment by crazybadger** [comment]
Brilliant, thank you!  Selecting just Amazon and Google does indeed work :-)

**Comment by th0mcat** [comment]
Once I click "Fetch Metadata", the entire GUI becomes unresponsive,  I'm able to close and re-open the "Fetch Metadata" menu, but am no longer presented with any options.  If I don't completely reboot the container, I'm unable to do **anything** in Calibre-Web.

**Comment by ThePrankMonkey** [comment]
Agreed, from the container I can't see how to disable the sources that are causing issues. Doesn't appear to be an Admin setting to disable them either, which would be great for when some dependent search engine breaks like this.

**Comment by MeisterLLD** [comment]
Same problem here, but even letting only Google and Amazon doesn't work. No choice of source works actually.

**Comment by lunik1** [comment]
Same for me but only the 豆瓣 engine causes an error

**Comment by PrynsTag** [comment]
I only encounter this error when `Amazon` and `豆瓣` is selected.

**Comment by mgoh99** [comment]
I'm having this issue too.  New nightly didn't fix it.  Logs read like this

ERROR {cps.metadata_provider.amazon:129} 503 Server Error: Service Unavailable for url: https://www.amazon.com/s?k[book]

**Comment by ThePrankMonkey** [comment]
I'm running `lscr.io/linuxserver/calibre-web:latest` [`e6e173cca5b7`] and the issue is resolved.

**Comment by pletse** [comment]
Hi guys

I've got the same problem as @mgoh99 has when I try to send my newly added epubs in calibre-web to my Kindle emailaddress.

I've tried the newest/latest version of Calibre-web today (9/01/2023) and I still have the same issue. I also using Linuxserver.io docker

If it's necessary that I open a new topic (error is the same although I perform a different action), I will do that 

(forgive me, I'm quite new to github)

**Comment by OzzieIsaacs** [comment]
Meanwhile I found the problem and fixed it, please update again to the now newest nightly version

**Comment by Vertux** [comment]
Unfortunately, the problem still exists. I first tried the latest stable build and it worked for a few books, but then the error popped up and did not go away. Then I switched to the nightly build, but that did not work either. It looks to me like the API access is being restricted by google, amazon, etc.

Version: 0.6.23 Beta - 0ff3f0f426bc51e7445ad49550e73832455a3eb9 - 2024-07-30T18:51:52+02:00
Docker Nightly build of [https://hub.docker.com/r/linuxserver/calibre-web](https://hub.docker.com/r/linuxserver/calibre-web)

[Error Log](https://pastebin.com/pyTvxGbs)

**Comment by RPSouto** [comment]
Same here.

In the last nightly any search with Google or Amazon returns error.

In the log I have the 429 (To many Request) for Google Api and 503 for Amazon.

**Comment by dylan-k** [comment]
Same here, on the latest version (Windows) the metadata search says "Search error!!" even with only Amazon and Google selected.

**Comment by yieldhog** [comment]
Also having this issue

**Comment by ArtemSmaznov** [comment]
yeah this is still an issue on 0.6.23 - d3233b4b9cf4ec540ff31fba787865cb95810ae3
just amazon and google works though

**Comment by NathanIfinity** [comment]
Yeah unchecking ComicVine fixes the issue, but is there a way to remove the broken sources?

**Comment by dylan-k** [comment]
ComicVine appears to be intermittently offline lately, but hopefully not broken forever.
Saw some conversation about that on Reddit at https://www.reddit.com/r/comicrackusers/comments/1fp8erk/comicvine_api_not_working/

**Comment by bvonsnack** [comment]
This is still an issue in June 2026! It's been four years.

**Comment by yieldhog** [comment]
Project is basically dead. I've moved on to https://grimmory.org and it's substantially better in my opinion.

**Comment by NathanIfinity** [comment]
I've migrated everything to bookorbit ! (Audiobook, ebooks, comic books)  it's amazing! 
https://bookorbit.app/

**Comment by bjoerns1983** [comment]
Works again with v 0.6.27
